server:
  port: 2003

spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: seata-account-service
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/seata_account?rewriteBatchedStatements=true&serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: 185450844
    type: com.alibaba.druid.pool.DruidDataSource

seata:
  tx-service-group: my_test_tx_group  # 与nacos事务分组配置项保持一致
  registry:  # 注册中心
    type: nacos
    nacos:
      application: seata-server      # seata-server注册在nacos中的服务名
      server-addr: 127.0.0.1:8848    # nacos的地址端口
      group: SEATA_GROUP            # seata-server在nacos的分组
      namespace: e2022ad8-89c9-4c4f-b390-0be2aa204f9b   # seata-server在nacos的命名空间ID
  config:  # 配置中心
    type: nacos
    nacos:
      server-addr: 127.0.0.1:8848
      group: SEATA_GROUP
      namespace: e2022ad8-89c9-4c4f-b390-0be2aa204f9b     # 与配置项命名空间ID保持一致
      dataId: seataServer.properties       # 与配置项Data Id保持一致

feign:
  hystrix:
    enabled: true
logging:
  level:
    io:
      seata: info
mybatis:
  mapperLocations: classpath:mapper/*.xml
