spring:
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      acks: 1
      retries: 3  #重试次数
      batch-size: 16384
      buffer-memory: 33554432
    consumer:
      group-id: test   # 组名，可根据配置修改
      enable-auto-commit: true  # 消费者消费之后是否自动提交
      auto-offset-reset: latest  #从最新的开始
      # key 和value的反序列化
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      properties:
        seesion:
          timeout:
            ms: 120000
        request:
          timeout:
            ms: 180000
      auto-commit-interval: 1000
      max-poll-records: 50
    listener:
      type: batch
  main:
    allow-circular-references: false
#      concurrency: 1
#      ack-mode: manual